# -*- coding: utf-8 -*-
"""Controlling light from bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QRxdufjAmPx2D6i5vxCKVWaR8GkGwaMx
"""

x = "Your username"#ADAFRUIT_IO_USERNAME
y = "Your Adafruit IO Key"#ADAFRUIT_IO_KEY

!pip install adafruit-io

from Adafruit_IO import Client, Feed, Data
aio = Client(x,y)

# create a feed
new = Feed(name='bot')

result = aio.create_feed(new)
result

!pip install python-telegram-bot

from Adafruit_IO import Data

from telegram.ext import Updater,CommandHandler
import requests

def on(bot,update):
  chat_id = update.message.chat_id    
  aio.create_data('bot',Data(value = 1))
  bot.send_message(chat_id =chat_id,text ="Lights On")
  

def off(bot,update):
  chat_id = update.message.chat_id
  aio.create_data('bot',Data(value = 0))
  bot.send_message(chat_id =chat_id,text ="Lights Off")

updater = Updater('1327257592:AAF5CGXLHBQaP0Gv1RltTPSqB1Fz1tf7Fzc')     #Use Telegram Token HTTP API
dp =updater.dispatcher
dp.add_handler(CommandHandler('on',on))
dp.add_handler(CommandHandler('off',off))
updater.start_polling()
updater.idle()
